apiVersion: v1
kind: Service
metadata:
  name: kubermatic-dl-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: kubermatic-dl

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: kubermatic-dl-deployment
spec:
    selector:
      matchLabels:
       app: kubermatic-dl
    replicas: 3
    template:
      metadata:
        labels:
          app: kubermatic-dl
      spec:
       containers:
       - name: kubermatic-dl
         image: dohko669/kubermatic-img:tagname
         imagePullPolicy: Always
         ports:
          - containerPort: 5080